---

- hosts: all
  become: true
  tasks:

  - name: Playbook to install apache and php on RedHat and also update repo cache
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: Playbook to install httpd and php package on Ubuntu and also update repo cache
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

