---

- hosts: all
  become: true
  tasks:

  - name: Playbook to install apache and php on RedHat and ubuntu also update repo cache, using variables for php and apache package.
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

